import { createIdFactory, makeRun } from "../common/document-model";
import type { BlockKind, TextBlock, TextRun } from "../common/types";
import {
  closest,
  elementsByTag,
  hasDescendant,
  type ParsedDocx,
  type XmlElement,
} from "./parser";

export interface DocxExtraction {
  blocks: TextBlock[];
  /** Run id → the `<w:t>` element it came from. */
  nodes: Map<string, XmlElement>;
  /** Paragraphs deliberately left alone, with the reason. */
  skipped: { location: string; reason: string }[];
}

function pStyle(paragraph: XmlElement): string | null {
  const props = elementsByTag(paragraph, "w:pStyle");
  for (const p of props) {
    // Only the paragraph's own style, not a nested paragraph's.
    if (closest(p, "w:p") === paragraph) return p.getAttribute("w:val");
  }
  return null;
}

function blockKind(paragraph: XmlElement): BlockKind {
  if (closest(paragraph.parentNode, "w:tc")) return "table-cell";

  const style = pStyle(paragraph) ?? "";
  if (/^Heading/i.test(style) || /^(Title|Subtitle)$/i.test(style)) return "heading";
  if (/Quote/i.test(style)) return "quote";

  for (const numPr of elementsByTag(paragraph, "w:numPr")) {
    if (closest(numPr, "w:p") === paragraph) return "list-item";
  }

  return "paragraph";
}

/**
 * Group a part's `<w:t>` elements into one block per paragraph.
 *
 * Grouping is done by walking up from each `<w:t>` to its nearest `<w:p>` rather than down
 * from paragraphs, so text inside nested structures (text boxes, nested tables) lands in
 * the paragraph that actually owns it instead of being counted twice.
 */
export function extractDocx(parsed: ParsedDocx): DocxExtraction {
  const nextBlockId = createIdFactory("db");
  const nextRunId = createIdFactory("dr");
  const blocks: TextBlock[] = [];
  const nodes = new Map<string, XmlElement>();
  const skipped: { location: string; reason: string }[] = [];

  for (const part of parsed.parts) {
    const grouped = new Map<XmlElement, TextRun[]>();
    const order: XmlElement[] = [];
    let loose = 0;

    for (const textEl of elementsByTag(part.root, "w:t")) {
      // Field display text (TOC entries, page numbers, cross-references) is regenerated by
      // Word from its instruction code. Rewriting it would be overwritten or wrong.
      if (closest(textEl, "w:fldSimple")) continue;

      const paragraph = closest(textEl, "w:p");
      if (!paragraph) {
        loose++;
        continue;
      }

      if (!grouped.has(paragraph)) {
        grouped.set(paragraph, []);
        order.push(paragraph);
      }

      const id = nextRunId();
      grouped.get(paragraph)!.push(makeRun(id, textEl.textContent ?? ""));
      nodes.set(id, textEl);
    }

    if (loose > 0) {
      skipped.push({
        location: part.path,
        reason: `${loose} text element(s) outside any paragraph were left unchanged.`,
      });
    }

    for (const paragraph of order) {
      const runs = grouped.get(paragraph)!;

      if (hasDescendant(paragraph, "w:instrText")) {
        for (const run of runs) nodes.delete(run.id);
        skipped.push({
          location: part.path,
          reason: "A paragraph containing a Word field (e.g. a table of contents entry or page reference) was left unchanged.",
        });
        continue;
      }

      if (!runs.some((r) => r.core.length > 0)) {
        for (const run of runs) nodes.delete(run.id);
        continue;
      }

      blocks.push({ id: nextBlockId(), kind: blockKind(paragraph), runs });
    }
  }

  return { blocks, nodes, skipped };
}
